version: "3.7"
services:
  contacts:
    build: .
    ports:
      - 8000
    environment:
      DATABASE_URL: postgresql://postgres@my-secret:database/contacts
    depends_on:
      - database
  database:
    image: postgres:12.2-alpine
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: my-secret
